# created_with_eee -- maintainer tooling for syncing content across hosts.
#
# Trezor-signing steps (commit, push) are meant to be run interactively by a
# human at the keyboard, confirming each physical device prompt yourself --
# no target here invokes trezor-agent on its own.

SPLIT_PROJECTS_DIR ?= $(HOME)/work/greek/git/gitlab/EEE-project
SPLIT_PROJECTS := created-with-eee-odyssey created-with-eee-palaestra created-with-eee-b1glc

GITHUB_PAGES_DIR ?= $(HOME)/work/greek/git/github/EEE-project/created_with_eee-pages-worktree
GITLAB_UNIFIED_PAGES_DIR ?= $(HOME)/work/greek/git/gitlab/EEE-project/created_with_eee-pages-worktree
PAGES_DIR ?= $(CURDIR)/../created_with_eee-pages-worktree

EEE_PYTHON ?= $(HOME)/.venv/eee/bin/python3

.PHONY: help sync-main fix-split-roots fix-gitlab-unified-scope fix-static-footer fix-split-hub-links export-notebooks verify-pages-deploy check-vocab

help:
	@echo "Targets:"
	@echo "  sync-main           Sync this repo's main branch to Codeberg, GitHub, and"
	@echo "                      GitLab (wraps ~/work/greek/git/push). Trezor-confirmed"
	@echo "                      per host as you run it."
	@echo "  fix-split-roots     Re-apply the session-page _ROOT fix (see"
	@echo "                      tools/fix-split-session-root.py) to local checkouts of the 3"
	@echo "                      split GitLab projects. Only edits files locally --"
	@echo "                      review with git status/diff, then commit + push each"
	@echo "                      by hand (Trezor-confirmed)."
	@echo "  fix-gitlab-unified-scope"
	@echo "                      Re-apply GitLab-unified-specific scope (see"
	@echo "                      tools/fix-gitlab-unified-pages-scope.py) after any"
	@echo "                      'git reset --hard codeberg/pages' on"
	@echo "                      GITLAB_UNIFIED_PAGES_DIR: removes the split-off"
	@echo "                      odyssey/palaestra/kapodistrias/kavafis_ithaki/zorba"
	@echo "                      content and restores .gitlab-ci.yml, neither of which"
	@echo "                      exists on Codeberg's pages branch to reset 'back' to."
	@echo "                      MANDATORY after every such reset -- has silently"
	@echo "                      regressed live Pages twice without it. Idempotent,"
	@echo "                      only edits files locally -- review, then commit + push"
	@echo "                      by hand (Trezor-confirmed)."
	@echo "  fix-static-footer   Re-apply the static hub footer host fix (see"
	@echo "                      tools/fix-static-footer-host.py) to GitHub + GitLab local"
	@echo "                      checkouts. Requires GITHUB_PAGES_DIR and"
	@echo "                      GITLAB_UNIFIED_PAGES_DIR checked out on the pages"
	@echo "                      branch (a worktree, not a branch switch, if the main"
	@echo "                      checkout needs to stay on main) -- only edits files"
	@echo "                      locally, review + commit + push by hand per host."
	@echo "  fix-split-hub-links Re-apply the split-project hub card-link fix (see"
	@echo "                      tools/fix-split-hub-card-links.py) to b1glc's local"
	@echo "                      checkout -- the only split project with its own"
	@echo "                      internal card-hub (odyssey/palaestra are flat lesson"
	@echo "                      lists, no equivalent bug). Only edits files locally,"
	@echo "                      review + commit + push by hand."
	@echo "  export-notebooks    Re-export NOTEBOOKS (space-separated source paths) to"
	@echo "                      WASM into PAGES_DIR (default: a sibling"
	@echo "                      created_with_eee-pages-worktree checked out on pages)."
	@echo "                      Example: make export-notebooks NOTEBOOKS=\""
	@echo "                      modern_greek/ellinika_b/chapter_01/chapter_01_notebook.py\""
	@echo "                      Only writes local files -- review, then commit + push by"
	@echo "                      hand per host (Trezor-confirmed). Hub pages (card lists,"
	@echo "                      index.tsv-driven) are not regenerated by this target."
	@echo "  verify-pages-deploy Check whether Pages deployments are actually serving"
	@echo "                      current content (not just pushed) across all 6 known"
	@echo "                      sites -- host deploy-status APIs (gh/glab) plus a live"
	@echo "                      fetch everywhere. Read-only, no Trezor step. Optional"
	@echo "                      SITE= filters to sites whose name matches, e.g."
	@echo "                      make verify-pages-deploy SITE=odyssey"
	@echo "  check-vocab         Find vocab TSVs where 2 different Greek words share"
	@echo "                      the same Translation value (unanswerable in a quiz)."
	@echo "                      Read-only. Optional SCOPE= limits to one course, e.g."
	@echo "                      make check-vocab SCOPE=modern_greek/ellinika_b"
	@echo ""
	@echo "NOT automated here (still manual -- see README's Maintainer tooling"
	@echo "section): hub regeneration and splitting a new course off into its own"
	@echo "GitLab project."

sync-main:
	$(HOME)/work/greek/git/push

fix-split-roots:
	python3 tools/fix-split-session-root.py $(foreach p,$(SPLIT_PROJECTS),$(SPLIT_PROJECTS_DIR)/$(p))
	@echo ""
	@echo "Local files only -- review with 'git status'/'git diff' in each project"
	@echo "directory above, then commit + push by hand (Trezor-confirmed, one at a"
	@echo "time). This target never commits or pushes."

fix-gitlab-unified-scope:
	python3 tools/fix-gitlab-unified-pages-scope.py $(GITLAB_UNIFIED_PAGES_DIR)
	@echo ""
	@echo "Local files only -- review with 'git status'/'git diff' in"
	@echo "GITLAB_UNIFIED_PAGES_DIR, then commit + push by hand (Trezor-confirmed)."
	@echo "This target never commits or pushes."

fix-static-footer:
	python3 tools/fix-static-footer-host.py --host https://github.com/EEE-project $(GITHUB_PAGES_DIR)
	python3 tools/fix-static-footer-host.py --host https://gitlab.com/EEE-project $(GITLAB_UNIFIED_PAGES_DIR) $(foreach p,$(SPLIT_PROJECTS),$(SPLIT_PROJECTS_DIR)/$(p))
	@echo ""
	@echo "Local files only -- review with 'git status'/'git diff' in each checkout"
	@echo "above, then commit + push by hand (Trezor-confirmed, one at a time). This"
	@echo "target never commits or pushes. Codeberg needs no fix -- it's the default."

fix-split-hub-links:
	python3 tools/fix-split-hub-card-links.py --prefix /created_with_eee/modern_greek/b1greeklanguageandculture/ $(SPLIT_PROJECTS_DIR)/created-with-eee-b1glc
	@echo ""
	@echo "Local files only -- review with 'git status'/'git diff' in the project"
	@echo "directory above, then commit + push by hand (Trezor-confirmed). This"
	@echo "target never commits or pushes."

export-notebooks:
	$(EEE_PYTHON) tools/export-notebooks.py --pages-dir $(PAGES_DIR) $(NOTEBOOKS)
	@echo ""
	@echo "Exported into $(PAGES_DIR) -- review with 'git status'/'git diff' there,"
	@echo "then commit + push by hand per host (Trezor-confirmed). This target never"
	@echo "commits or pushes, and only touches Codeberg's pages worktree -- copy the"
	@echo "exported directories into GITHUB_PAGES_DIR / GITLAB_UNIFIED_PAGES_DIR /"
	@echo "SPLIT_PROJECTS_DIR checkouts separately (the export itself is host-portable,"
	@echo "no need to re-run per host)."

verify-pages-deploy:
	SPLIT_PROJECTS="$(SPLIT_PROJECTS)" python3 tools/verify-pages-deploy.py $(SITE)

check-vocab:
	python3 tools/check-vocab-collisions.py $(SCOPE)
