# UniMorph grc slot templates — English labels

[[noun.slots]]
tag_type = "unimorph"
tag = "N;NOM;SG"
label = "Nom. Sg."

[[noun.slots]]
tag_type = "unimorph"
tag = "N;NOM;PL"
label = "Nom. Pl."

[[noun.slots]]
tag_type = "unimorph"
tag = "N;GEN;SG"
label = "Gen. Sg."

[[noun.slots]]
tag_type = "unimorph"
tag = "N;GEN;PL"
label = "Gen. Pl."

[[noun.slots]]
tag_type = "unimorph"
tag = "N;DAT;SG"
label = "Dat. Sg."

[[noun.slots]]
tag_type = "unimorph"
tag = "N;DAT;PL"
label = "Dat. Pl."

[[noun.slots]]
tag_type = "unimorph"
tag = "N;ACC;SG"
label = "Acc. Sg."

[[noun.slots]]
tag_type = "unimorph"
tag = "N;ACC;PL"
label = "Acc. Pl."

[[noun.slots]]
tag_type = "unimorph"
tag = "N;VOC;SG"
label = "Voc. Sg."

[[noun.slots]]
tag_type = "unimorph"
tag = "N;VOC;PL"
label = "Voc. Pl."
