#!/usr/bin/env python3
"""Find dead links on the static hub pages of every created_with_eee host.

Crawls from each start URL (default: the Codeberg, GitHub and GitLab roots)
through the hub pages generated by tools/gen_hub.py -- cards, back links,
icons -- and lists every internal link or asset that does not answer with
HTTP < 400. Lesson pages are only status-checked, never parsed. Read-only.

Usage:
    python3 tools/check-hub-links.py [--max-depth N] [<start-url> ...]

Exit status 1 if any link is dead. A page counts as a hub if it carries the
generated card / back-link markup; links leaving the three Pages hosts are
not followed.
"""
import argparse
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor

START_URLS = [
    "https://eee-project.codeberg.page/created_with_eee/",
    "https://eee-project.github.io/created_with_eee/",
    "https://eee-project.gitlab.io/created_with_eee/",
]
PAGES_HOSTS = ("codeberg.page", "github.io", "gitlab.io")
LINK = re.compile(r'(?:href|src)="([^"#]+)"')
HUB = re.compile(r'class="(?:eee-card|tb-back)')  # markup only the generated hub pages carry


def fetch(url: str, method: str = "GET") -> tuple[int | str, str, str]:
    """(status, body, final url); the status is the exception's name when nothing answered."""
    request = urllib.request.Request(url, method=method, headers={"User-Agent": "eee-check-hub-links"})
    try:
        with urllib.request.urlopen(request, timeout=45) as response:
            body = response.read(400_000).decode("utf-8", "replace") if method == "GET" else ""
            return response.status, body, response.geturl()
    except urllib.error.HTTPError as e:
        return e.code, "", url
    except Exception as e:  # timeout, DNS, TLS
        return type(e).__name__, "", url


def status_of(url: str) -> tuple[int | str, str, str]:
    """HEAD first; GET when the server refuses HEAD or answers flakily."""
    status, _, final = fetch(url, "HEAD")
    if status in (403, 405, 501) or not isinstance(status, int) or status >= 500:
        status, _, final = fetch(url)
    return status, "", final


def alive(status: int | str) -> bool:
    return isinstance(status, int) and status < 400


def crawl(start_urls: list[str], max_depth: int) -> tuple[int, int, dict[str, tuple[int | str, str]]]:
    """(hub pages parsed, URLs checked, {dead url: (status, page that links to it)})."""
    seen: set[str] = set()
    dead: dict[str, tuple[int | str, str]] = {}
    hubs = 0
    level = {url: "(start)" for url in start_urls}
    for depth in range(max_depth):
        last = depth == max_depth - 1  # deepest level: status only
        todo = {url: parent for url, parent in level.items() if url not in seen}
        with ThreadPoolExecutor(max_workers=8) as pool:
            answers = list(zip(todo, pool.map(status_of if last else fetch, todo)))
        level = {}
        for url, (status, body, final) in answers:
            seen.add(url)
            if not alive(status):
                dead[url] = (status, todo[url])
            elif not last and HUB.search(body):
                hubs += 1
                for raw in LINK.findall(body):
                    target = urllib.parse.urljoin(final, raw)
                    if urllib.parse.urlparse(target).netloc.endswith(PAGES_HOSTS):
                        level.setdefault(target, url)
    return hubs, len(seen), dead


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--max-depth", type=int, default=5, help="Levels to follow from each start URL (default 5: root, category, course, sub-course hub, lesson)")
    parser.add_argument("start_urls", nargs="*", help="Where to start (default: the Codeberg, GitHub and GitLab roots)")
    args = parser.parse_args()

    hubs, checked, dead = crawl(args.start_urls or START_URLS, args.max_depth)
    print(f"{hubs} hub pages parsed, {checked} URLs checked, {len(dead)} dead")
    for url, (status, parent) in dead.items():
        print(f"  DEAD [{status}] {url}\n        linked from {parent}")
    sys.exit(1 if dead else 0)


if __name__ == "__main__":
    main()
